### ISSUE TITLE
Pull Request and Issue Templates

### ISSUE THREAD

**Issue by emanuelhaine** [zopencommunity/meta#838]
Hello team!

I want to propose Pull Request Templates, and since I am proposing this. I want to work on this, if possible, of course.

Just to track this issue, I'll create a task list to map the PRs

- [ ] Issue Templates
  - [ ] bug-report
  - [ ] feature-request
  - [ ] documentation (creation or enhancement)
- [ ] PR template →  #841

**Comment by IgorTodorovskiIBM** [comment]
That's a good idea. Any repos you plan to model this off of? This could also be extended to issue templates

**Comment by emanuelhaine** [comment]
Just to track this issue, I'll create a task list to map the PRs

**Issue templates**
- [ ] bug-report
- [ ] feature-request
- [ ] documentation (creation or enhancement)

Pull Request template

- [ ] PR template

**Comment by IgorTodorovskiIBM** [comment]
Let's close this since the issue templates and PR templates are now done
