### ISSUE TITLE
Quick Start Link Broken

### ISSUE THREAD

**Issue by dkelosky** [zopencommunity/meta#889]
### Description

The quick start link does not resolve to the guide from here https://github.com/zopencommunity/meta?tab=readme-ov-file#installation-and-sample-usage

### Severity

Sev 4 - Low

**Comment by IgorTodorovskiIBM** [comment]
Are you able to provide the associated link?

**Comment by dkelosky** [comment]
Sorry I had a copy/paste failure. The link is under here: https://github.com/zopencommunity/meta?tab=readme-ov-file#installation-and-sample-usage

**Comment by sachintu47** [comment]
Closed as part of commit https://github.com/zopencommunity/meta/commit/2b9516e4829105c969831ee32afab83cf10485e3
