### ISSUE TITLE
[New Port]: git-chglog

### ISSUE THREAD

**Issue by v1gnesh** [zopencommunity/meta#919]
### Port Description

CHANGELOG generator implemented in Go (Golang). Anytime, anywhere, Write your CHANGELOG.

### Upstream Repository URL

https://github.com/git-chglog/git-chglog

**Comment by IgorTodorovskiIBM** [comment]
Repository created: https://github.com/zopencommunity/git-chglogport

**Comment by v1gnesh** [comment]
Awesome, glad that this method worked!
