### ISSUE TITLE
[New Port]: zedc

### ISSUE THREAD

**Issue by sachintu47** [zopencommunity/meta#925]
### Port Description

The zlib data compression library provides in-memory compression and decompression functions, including integrity checks of the uncompressed data. A modified version of the zlib compression library is used by zEDC. The IBM-provided zlib compatible C library provides a set of wrapper functions that use zEDC compression when appropriate and when zEDC is not appropriate, software-based compression services are used.

### Additional Information (Optional)

This project only exports the IBM zedc flags, header and library paths.

**Comment by zosopentoolsmain** [comment]
Repository created: https://github.com/zopencommunity/zedcport
